WorkoutBuddy/config/routes.rb
Rails.application.routes.draw do
    root 'welcome#new'

    get 'users/new' => 'users#new', :as => 'users'
    post 'users/new' => 'users#create'

    get'/center' => 'center#new'

  get 'signup' => 'users#new'
  resources :users

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'

end

WorkoutBuddy/app/models/profile.rb
class Profile < ActiveRecord::Base
end

WorkoutBuddy/app/models/user.rb
class User < ActiveRecord::Base

    has_secure_password

end

WorkoutBuddy/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
    redirect_to '/login' unless current_user
  end
end

WorkoutBuddy/app/controllers/center_controller.rb
class CenterController < ApplicationController
    before_action :require_user, only: [:new]
    layout 'center' 
    
    def new
    end

end

WorkoutBuddy/app/controllers/editStats_controller.rb
class EditStatsController < ApplicationController
    def modify
        @profile = Profile.new(profile_params)
            render 'editStats'
            #redirect_to '/profile'
end

WorkoutBuddy/app/controllers/profile_controller.rb
class ProfileController < ApplicationController

def edit
    @profiles = Profile.all
end

end

WorkoutBuddy/app/controllers/registration_controller.rb
class RegistrationController < ApplicationController
    def new
        @profile = Profile.new
    end

    def create
        @profile = Profile.new(profile_params)
        if @profile.save
            redirect_to '/profile'
        else
            render 'new'
        end
    end

    private
    def profile_params
        params.require(:profile)
        .permit(:first_name)
        .permit(:last_name)
    end
end

WorkoutBuddy/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end

    def create
        @user = User.find_by_email(params[:session][:email])
        if @user && @user.authenticate(params[:session][:password])
            session[:user_id] = @user.id
            redirect_to '/center'
        else
            redirect_to '/login'
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to '/login'
    end

end

WorkoutBuddy/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to '/center'
        else
            redirect_to '/users/new'
        end
    end

    def confirm
        @user = User.last
    end

    def show
        @user = User.find(params[:id])
    end

    def edit
        @user = User.find(params[:id])
    end

    private
    def user_params
        params.require(:user)
        .permit(:first_name, :last_name, :email, :password)
    end
end

WorkoutBuddy/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

def new
end

end

WorkoutBuddy/app/helpers/application_helper.rb
module ApplicationHelper
end

WorkoutBuddy/app/helpers/center_helper.rb
module CenterHelper
end

WorkoutBuddy/app/helpers/profile_helper.rb
module ProfileHelper
end

WorkoutBuddy/app/helpers/registration_helper.rb
module RegistrationHelper
end

WorkoutBuddy/app/helpers/sessions_helper.rb
module SessionsHelper
end

WorkoutBuddy/app/helpers/users_helper.rb
module UsersHelper
end

WorkoutBuddy/app/helpers/welcome_helper.rb
module WelcomeHelper
end

WorkoutBuddy/app/views/center/new.html.erb
<!-- Map -->
<div id="googleMap"></div>
	
	<div id="menu"> 
		<table>
			<div id="profilePic"></div> 
			<tr>
				<td id="name">John Smith</td> 
			</tr>
			<tr>
				<td id="blank"></td> 
			</tr>
			<tr>
				<td id="gender">Gender: </td>
			</tr>
			<tr>
				<td id="height">Height: </td>
			</tr>
			<tr>
				<td id="weight">Weight: </td>
			</tr>
			<tr>
				<td id="experience">Experience: </td>
			</tr>
		</table>

	</div>


<script>
var myCenter =new google.maps.LatLng(32.7150,-117.1625);

google.maps.event.addDomListener(window, 'load', function(){
    //Google map view
	var mapProp = {
	center: myCenter,
	zoom:11,
	mapTypeId:google.maps.MapTypeId.ROADMAP
	};
	var map=new google.maps.Map(document.getElementById("googleMap"),mapProp);

	var marker = new google.maps.Marker({
		position: myCenter,
	});

	marker.setMap(map);	
});

</script>

WorkoutBuddy/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WorkoutBuddy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="header">
<h1 id="title">Workout Buddy</h1>
</div>

<%= yield %>

<div class="footer">
<p>Made by MattMattAndyBrandon</p>
</div>

</body>
</html>

WorkoutBuddy/app/views/layouts/center.html.erb
<!DOCTYPE html>
<html>
<head>
<script src="http://maps.googleapis.com/maps/api/js"></script>
<%= javascript_include_tag 'center', 'data-turbolinks-track' => true %>
<%= stylesheet_link_tag 'center', media: 'all',
    'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
</head>

<body class="<%= controller_name %> <%=action_name %>">
    <nav class="tab-bar">
      <button class="tab-btn tab-1 selected">Map</button>
      <button class="tab-btn tab-2">Equipment</button>
      <button class="tab-btn tab-3">Diet</button>
      <button class="tab-btn tab-4">Others</button>
      <button class="tab-btn tab-5" id="logout">
      <%= link_to "Log out", logout_path, method: "delete"%>
      </button>
    </nav>

	<div id="googleMap"></div>
	
	<div id="menu"> 
    <%= link_to "Edit Profile", "app/views/users/editStats"%>
		<table>
			<div id="profilePic"></div> 
			<tr>
				<td id="name">John Smith</td> 
			</tr>
			<tr>
				<td id="blank"></td> 
			</tr>
			<tr>
				<td id="gender">Gender: </td>
			</tr>
			<tr>
				<td id="height">Height: </td>
			</tr>
			<tr>
				<td id="weight">Weight: </td>
			</tr>
			<tr>
				<td id="experience">Experience: </td>
			</tr>
		</table>

	</div>
  
</body>

<script>
var myCenter =new google.maps.LatLng(32.7150,-117.1625);

function initialize() {
    console.log("initialize");
//Google map view
	var mapProp = {
	center: myCenter,
	zoom:11,
	mapTypeId:google.maps.MapTypeId.ROADMAP
	};
	var map=new google.maps.Map(document.getElementById("googleMap"),mapProp);

	var marker = new google.maps.Marker({
		position: myCenter,
	});

	marker.setMap(map);


//tab bar controller
	var tabBtns = document.querySelectorAll('.tab-bar > .tab-btn');

	for(var i = 0; i < tabBtns.length; i++) {   tabBtns[i].addEventListener('click', onTabClick, true);
	}

	function onTabClick(e) {
	var currentTab = document.querySelector('.tab-bar > .tab-btn.selected');
	if(currentTab) {
	  currentTab.classList.remove('selected');
	}
	var btn = e.target;
	btn.classList.add('selected');
	}
	
	
	


	
}

    google.maps.event.addDomListener(window, 'load', initialize);
</script>

</html>

WorkoutBuddy/app/views/users/confirm.html.erb
<div class="confirm_page">
    <p>You entered the following data:</p>

    <p>First name: <%=@user.first_name%></p>
    <p>Last name: <%=@user.last_name%></p>
    <p>Email: <%=@user.email%></p>
    <p>Password: <%=@user.password_digest%></p>
    <%= link_to "Continue", '/center' %>
</div>

WorkoutBuddy/app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%#= render 'shared/error_messages' %>

      <%= f.label :first_name %>
      <%= f.text_field :first_name, class: 'form-control' %>

      <%= f.label :last_name %>
      <%= f.text_field :last_name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%#= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">change</a>
    </div>
  </div>
</div>

WorkoutBuddy/app/views/users/editStats.html.erb
<% provide(:title, "Edit user statistics") %>
<h1>Update your stats!</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%#= render 'shared/error_messages' %>

      <%= f.label :gender %>
      <%= f.text_field :gender, class: 'form-control' %>

      <%= f.label :weight %>
      <%= f.text_field :weight, class: 'form-control' %>

      <%= f.label :height %>
      <%= f.test_field :height, class: 'form-control' %>

      <%= f.label :experience %>
      <%= f.text_field :experience, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

WorkoutBuddy/app/views/users/new.html.erb
<h1 id="registration_title">Register:</h1>
<%= form_for(@user) do |f| %>
    <%= f.text_field :first_name, :placeholder => "First name"%> <br/>
    <%= f.text_field :last_name, :placeholder => "Last name"%>  <br/>
    <%= f.email_field :email, :placeholder => "Email"%> <br/>
    <%= f.password_field :password, :placeholder => "Password"%> <br/>

    <div class="submit_registration">
        <%= f.submit "Submit" %>
    </div>
<% end %>

WorkoutBuddy/app/views/users/show.html.erb
<%= @user.first_name %>, <%= @user.email %>

render :action => 'show'

WorkoutBuddy/app/views/welcome/new.html.erb
<%= javascript_include_tag 'welcome' %>
<div id="loginBox">
    <div id="loginInfo">
      <div id="loginBoxEmail" class="box">
        <form>Email<br>
          <input id="emailBox" type="text" name="Email">
        </form>
      </div>
      <div id="loginBoxPass" class="box">
         <form>Password
           <input id="passwordBox" type="password" name="Password">
         </form>
      </div>
      <div id="loginButton">
        <%= link_to "Login", "/users/verify"%>
      </div>
    </div>
      <!--<button id="signInButton" onclick="showDiv();">Sign In</button>-->
      <span class="home_buttons">
          <!--<a id="signInButton">Sign In</a>-->
          <%= link_to "Login", "/login"%>
          <%= link_to "Register", "/users/new"%> 
      </span>
</div>